### ISSUE TITLE
dm_cohort does not exist

### ISSUE THREAD

**Issue by gsk1692** [alistairewj/reproducibility-mimic#3]
I executed the make_all.sql file and it throws this error, along with lots of other errors.

I built the postgres database and ran the make_all.sql from queries folder. Am I missing something?

I need to be able to run the notebooks.

Please provide a solution. Thanks in advance.

**Comment by alistairewj** [comment]
What error does it throw? You haven't provided any detail.

**Comment by gsk1692** [comment]
psql:dm_word_count.sql:16: ERROR:  function poslen(tsvector) does not exist
LINE 3:   hadm_id, sum(poslen(to_tsvector(text))) as non_stop_words
                       ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:dm_obs_count.sql:4: NOTICE:  table "dm_obs_count" does not exist, skipping
DROP TABLE
SELECT 61532
psql:dm_cohort.sql:1: NOTICE:  table "dm_cohort" does not exist, skipping
DROP TABLE
psql:dm_cohort.sql:433: ERROR:  relation "dm_word_count" does not exist
LINE 377: left join dm_word_count wc
                    ^
DROP TABLE
SELECT 60187
DROP TABLE
SELECT 52726
DROP TABLE
SELECT 2961
psql:dm_static_data.sql:2: NOTICE:  table "dm_static_data" does not exist, skipping
DROP TABLE
psql:dm_static_data.sql:130: ERROR:  relation "dm_cohort" does not exist
LINE 103: FROM dm_cohort co
               ^

These are the errors I am getting... (while executing make_all.sql)

**Comment by alistairewj** [comment]
You need to install the TSExact extension as described in the README - at the moment this is unavailable for postgres 10+ so you will need to downgrade to 9 for the interim. Issue #2 is tracking postgres 10 support.

**Comment by gsk1692** [comment]
Oh ok... I had installed that...
I am using Postgres 9.5
Should I try re installing?

**Comment by alistairewj** [comment]
It sounds like maybe you installed it but didn't activate it on the
database. After installing TSExact on your computer, you have to create the
extension on the database. Connect to the database and run `CREATE
EXTENSION tsexact;`

**Comment by gsk1692** [comment]
Yes! Thank you so much. I found that the command had not worked when I executed it from my user account (not from Postgres user). 

When I run the same from psql shell, it worked!

Thank you for the assistance 👍  and my apologies for the trouble :)
 
Closing the issue...
