### ISSUE TITLE
Memory Error when getting data from database in reproducibility notebook 

### ISSUE THREAD

**Issue by safynaz** [alistairewj/reproducibility-mimic#7]
Hi, i get the following error when run cell 2 in reproducibility notebook to get data:

MemoryError                               Traceback (most recent call last)
<ipython-input-2-8d51989992c8> in <module>
     46     # Wall time: 2min 7s
     47 
---> 48     df = pd.read_sql_query(query_schema + 'select * from mp_data', con)
     49     df.drop('subject_id',axis=1,inplace=True)
     50     df.drop('hadm_id',axis=1,inplace=True)

~\Anaconda3\envs\py3\lib\site-packages\pandas\io\sql.py in read_sql_query(sql, con, index_col, coerce_float, params, parse_dates, chunksize)
    312     return pandas_sql.read_query(
    313         sql, index_col=index_col, params=params, coerce_float=coerce_float,
--> 314         parse_dates=parse_dates, chunksize=chunksize)
    315 
    316 

~\Anaconda3\envs\py3\lib\site-packages\pandas\io\sql.py in read_query(self, sql, index_col, coerce_float, params, parse_dates, chunksize)
   1480             frame = _wrap_result(data, columns, index_col=index_col,
   1481                                  coerce_float=coerce_float,
-> 1482                                  parse_dates=parse_dates)
   1483             return frame
   1484 

~\Anaconda3\envs\py3\lib\site-packages\pandas\io\sql.py in _wrap_result(data, columns, index_col, coerce_float, parse_dates)
    139 
    140     frame = DataFrame.from_records(data, columns=columns,
--> 141                                    coerce_float=coerce_float)
    142 
    143     frame = _parse_date_columns(frame, parse_dates)

~\Anaconda3\envs\py3\lib\site-packages\pandas\core\frame.py in from_records(cls, data, index, exclude, columns, coerce_float, nrows)
   1510         else:
   1511             arrays, arr_columns = to_arrays(data, columns,
-> 1512                                             coerce_float=coerce_float)
   1513 
   1514             arr_columns = ensure_index(arr_columns)

~\Anaconda3\envs\py3\lib\site-packages\pandas\core\internals\construction.py in to_arrays(data, columns, coerce_float, dtype)
    402     if isinstance(data[0], (list, tuple)):
    403         return _list_to_arrays(data, columns, coerce_float=coerce_float,
--> 404                                dtype=dtype)
    405     elif isinstance(data[0], compat.Mapping):
    406         return _list_of_dict_to_arrays(data, columns,

~\Anaconda3\envs\py3\lib\site-packages\pandas\core\internals\construction.py in _list_to_arrays(data, columns, coerce_float, dtype)
    429 def _list_to_arrays(data, columns, coerce_float=False, dtype=None):
    430     if len(data) > 0 and isinstance(data[0], tuple):
--> 431         content = list(lib.to_object_array_tuples(data).T)
    432     else:
    433         # list of lists

pandas/_libs/lib.pyx in pandas._libs.lib.to_object_array_tuples()

MemoryError: 

Please help me to solve it 
Thanks alot

**Comment by alistairewj** [comment]
Probably you don't have enough RAM on your computer to load the entire table into memory.

**Comment by safynaz** [comment]
what's RAM requirement to execute it ???
I have 8 G RAM intel Core i5

**Comment by alistairewj** [comment]
I have 64gb of RAM so I guess the answer is more than 8 but no more than 64 :)

**Comment by safynaz** [comment]
Ok i will update my PC, 
Many Thanks for your reply :)

**Comment by alistairewj** [comment]
Yep or you can read up about increasing the swap which will slow things down but give you an immediate solution.
